### PR TITLE
Augmenting negative data with random synthetic data

### PR DESCRIPTION
**Pull request by raphael-64**

### CODE REVIEW

**Review by BrianZhang1 — COMMENTED** [review]
interesting concept of generating synthetic data for negative examples, good idea since that's generally the gap in our dataset that makes the model less effective. The code looks good to me, have you gotten the chance to use the synthetic data to train a model and roughly see how it affects performance?

**Comment by raphael-64** [comment]
yes it seems to slightly improve performance by around 1-2%, i'll do some more testing rn and get some more feedback

**Comment by raphael-64** [comment]
testing with closed fist, thumbs up and finger gun showed the model had slightly higher AUC-ROC and AUC-PR but no significant effect on accuracy/loss (pretty much the same)

**Review by BrianZhang1 — APPROVED** [review]
alright, looks good to me

**Pull request merged**
